
function defaultStyle1()
{
    resetUnusedClasses();
    jQuery("#hc_default_template").val(1);
    jQuery(".connectorWrapper").css("height","600px");
    jQuery("#connectorHeightSlider").slider("value", "600");
    jQuery("#connectorHeight").val("600px");
    jQuery(".connectorWrapper").css("width","194px");
    jQuery("#connectorWidthSlider").slider("value", "194");
    jQuery("#connectorWidth").val("194px");
    jQuery(".optinWrapper").css("height","194px");
    jQuery("#callToActionHeightSlider").slider("value", "194");
    jQuery("#callToActionHeight").val("194px");
    jQuery(".emailConnectorWrapper").css("height","643px");
    jQuery("#emailBoxHeightSlider").slider("value", "643");
    jQuery("#emailBoxHeight").val("643px");
    jQuery(".facebookConnectorWrapper").css("height","562px");
    jQuery("#facebookBoxHeightSlider").slider("value", "562");
    jQuery("#facebookBoxHeight").val("562px");
    jQuery(".oneClickConnectorWrapper").css("height","582px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "582");
    jQuery("#oneClickBoxHeight").val("582px");
    jQuery(".emailOptinWrapper").css("height","185px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "185");
    jQuery("#emailCallToActionHeight").val("185px");
    jQuery(".facebookOptinWrapper").css("height","112px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "112");
    jQuery("#facebookCallToActionHeight").val("112px");
    jQuery(".oneClickOptinWrapper").css("height","128px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "128");
    jQuery("#oneClickCallToActionHeight").val("128px");
    jQuery("p.connectorHeadline").css("font-size","25px");
    jQuery("#headlineFontSizeSlider").slider("value", "25");
    jQuery("#headlineFontSize").val("25px");
    jQuery("div.connectorDescriptionText").css("font-size","18px");
    jQuery("div.connectorDescriptionText p").css("font-size","18px");
    jQuery("div.connectorDescriptionText li").css("font-size","18px");
    jQuery("#mainFontSizeSlider").slider("value", "18");
    jQuery("#mainFontSize").val("18px");
    jQuery("p.connectorCallToAction").css("font-size","18px");
    jQuery("#callToActionFontSizeSlider").slider("value", "18");
    jQuery("#callToActionFontSize").val("18px");
    jQuery(".connectorWrapper").css("background-color","#bb0000");
    jQuery("input#connectorBGColor").miniColors('value', ["#bb0000"]);
    jQuery(".optinWrapper").css("background-color","#cb4d4d");
    jQuery("input#OptinBGColor").miniColors('value', ["#cb4d4d"]);
    jQuery("p.connecterHeadline").css("color","#ffffff");
    jQuery("input#headlineTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("border-color","#920000");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#920000"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#ffffff");
    jQuery("input#callToActionTextColor").miniColors('value', ["#ffffff"]);
    jQuery("a#emailSignUpButton").css("color","#ffffff");
    jQuery("a#oneClickSignupButton").css("color","#ffffff");
    jQuery("input#buttonFontColor").miniColors('value', ["#ffffff"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("border-color","#000000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#000000"]);
    jQuery("div.connectorDescriptionText").css("color","#ffffff");
    jQuery("div.connectorDescriptionText p").css("color","#ffffff");
    jQuery("div.connectorDescriptionText li").css("color","#ffffff");
    jQuery("input#bodyTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#000000");
    jQuery("input#borderColor").miniColors('value', ["#000000"]);
    jQuery(".optinGraphic").css("margin-top","-30px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-30");
    jQuery("#imageVerticalPosition").val("-30px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","berlin Sans FB");
    jQuery("select#headlineFont").val("berlin Sans FB");
    jQuery("input.connectorInputFields").css("font-family","berlin Sans FB");
    jQuery("select#inputTextFont").val("berlin Sans FB");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","berlin Sans FB");
    jQuery("select#callToActionFont").val("berlin Sans FB");
    jQuery("div.connectorDescriptionText").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText p").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText li").css("font-family","berlin Sans FB");
    jQuery("select#bodyFont").val("berlin Sans FB");
    jQuery(".navButton").css("background","#299100");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#299100), to(#207400))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #207400 5%, #299100 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#299100', endColorstr='#207400'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#299100"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("Enter your Name and Email Address Below");
    jQuery("#emailCallToActionText").val("Enter your Name and Email Address Below");
    jQuery("p.facebookCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#facebookCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.oneClickCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#oneClickCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("div.connectorDescriptionText").text("Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.");
    tinyMCE.activeEditor.setContent('Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.');
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
    jQuery('input#facebookButtonText').val('Sign Up!');
    facebookButtonText();
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("#sidePictureShow").attr("checked", true);
    jQuery("#individualHeightCheckbox").attr("checked", true);
    jQuery('tr.individualHeightSettings').show();
}
function defaultStyle2() {
    resetUnusedClasses();
    jQuery("#hc_default_template").val(2);
    jQuery(".connectorWrapper").css("height","557px");
    jQuery("#connectorHeightSlider").slider("value", "557");
    jQuery("#connectorHeight").val("557px");
    jQuery(".connectorWrapper").css("width","194px");
    jQuery("#connectorWidthSlider").slider("value", "194");
    jQuery("#connectorWidth").val("194px");
    jQuery(".optinWrapper").css("height","183px");
    jQuery("#callToActionHeightSlider").slider("value", "183");
    jQuery("#callToActionHeight").val("183px");
    jQuery(".emailConnectorWrapper").css("height","582px");
    jQuery("#emailBoxHeightSlider").slider("value", "582");
    jQuery("#emailBoxHeight").val("582px");
    jQuery(".facebookConnectorWrapper").css("height","521px");
    jQuery("#facebookBoxHeightSlider").slider("value", "521");
    jQuery("#facebookBoxHeight").val("521px");
    jQuery(".oneClickConnectorWrapper").css("height","530px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "530");
    jQuery("#oneClickBoxHeight").val("530px");
    jQuery(".emailOptinWrapper").css("height","189px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "189");
    jQuery("#emailCallToActionHeight").val("189px");
    jQuery(".facebookOptinWrapper").css("height","111px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "111");
    jQuery("#facebookCallToActionHeight").val("111px");
    jQuery(".oneClickOptinWrapper").css("height","124px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "124");
    jQuery("#oneClickCallToActionHeight").val("124px");
    jQuery("p.connectorHeadline").css("font-size","22px");
    jQuery("#headlineFontSizeSlider").slider("value", "22");
    jQuery("#headlineFontSize").val("22px");
    jQuery("div.connectorDescriptionText").css("font-size","16px");
    jQuery("div.connectorDescriptionText p").css("font-size","16px");
    jQuery("div.connectorDescriptionText li").css("font-size","16px");
    jQuery("#mainFontSizeSlider").slider("value", "16");
    jQuery("#mainFontSize").val("16px");
    jQuery("p.connectorCallToAction").css("font-size","18px");
    jQuery("#callToActionFontSizeSlider").slider("value", "18");
    jQuery("#callToActionFontSize").val("18px");
    jQuery(".connectorWrapper").css("background-color","#0051BB");
    jQuery("input#connectorBGColor").miniColors('value', ["#0051BB"]);
    jQuery(".optinWrapper").css("background-color","#4D6BCB");
    jQuery("input#OptinBGColor").miniColors('value', ["#4D6BCB"]);
    jQuery("p.connecterHeadline").css("color","#ffffff");
    jQuery("input#headlineTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("border-color","#920000");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#920000"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#ffffff");
    jQuery("input#callToActionTextColor").miniColors('value', ["#ffffff"]);
    jQuery("a#emailSignUpButton").css("color","#FFFFFF");
    jQuery("a#oneClickSignupButton").css("color","#FFFFFF");
    jQuery("input#buttonFontColor").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #fffffc");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #fffffc");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #fffffc");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#fffffc"]);
    jQuery("a.navButton").css("border-color","#000000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#000000"]);
    jQuery("div.connectorDescriptionText").css("color","#ffffff");
    jQuery("div.connectorDescriptionText p").css("color","#ffffff");
    jQuery("div.connectorDescriptionText li").css("color","#ffffff");
    jQuery("input#bodyTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#000000");
    jQuery("input#borderColor").miniColors('value', ["#000000"]);
    jQuery(".optinGraphic").css("margin-top","-30px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-30");
    jQuery("#imageVerticalPosition").val("-30px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","Droid Sans");
    jQuery("select#headlineFont").val("Droid Sans");
    jQuery("input.connectorInputFields").css("font-family","berlin Sans FB");
    jQuery("select#inputTextFont").val("berlin Sans FB");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Droid Sans");
    jQuery("select#callToActionFont").val("Droid Sans");
    jQuery("div.connectorDescriptionText").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText p").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText li").css("font-family","berlin Sans FB");
    jQuery("select#bodyFont").val("berlin Sans FB");
    jQuery(".navButton").css("background","#FFB30F");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#FFB30F), to(#cd8f0c))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #cd8f0c 5%, #FFB30F 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#FFB30F', endColorstr='#cd8f0c'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#FFB30F"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("Enter your Name and Email Address Below");
    jQuery("#emailCallToActionText").val("Enter your Name and Email Address Below");
    jQuery("p.facebookCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#facebookCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.oneClickCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#oneClickCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("div.connectorDescriptionText").text("Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.");
    tinyMCE.activeEditor.setContent('Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.');
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("#sidePictureShow").attr("checked", true);
    jQuery('input#facebookButtonText').val('Sign Up!');
    facebookButtonText();
}
function defaultStyle3() {
    resetUnusedClasses();
    jQuery("#hc_default_template").val(3);
    jQuery(".connectorWrapper").css("height","237px");
    jQuery("#connectorHeightSlider").slider("value", "237");
    jQuery("#connectorHeight").val("237px");
    jQuery(".connectorWrapper").css("width","521px");
    jQuery("#connectorWidthSlider").slider("value", "521");
    jQuery("#connectorWidth").val("521px");
    jQuery(".optinWrapper").css("height","98px");
    jQuery("#callToActionHeightSlider").slider("value", "98");
    jQuery("#callToActionHeight").val("98px");
    jQuery(".emailConnectorWrapper").css("height","237px");
    jQuery("#emailBoxHeightSlider").slider("value", "237");
    jQuery("#emailBoxHeight").val("237px");
    jQuery(".facebookConnectorWrapper").css("height","237px");
    jQuery("#facebookBoxHeightSlider").slider("value", "237");
    jQuery("#facebookBoxHeight").val("237px");
    jQuery(".oneClickConnectorWrapper").css("height","237px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "237");
    jQuery("#oneClickBoxHeight").val("237px");
    jQuery(".emailOptinWrapper").css("height","98px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "98");
    jQuery("#emailCallToActionHeight").val("98px");
    jQuery(".facebookOptinWrapper").css("height","98px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "98");
    jQuery("#facebookCallToActionHeight").val("98px");
    jQuery(".oneClickOptinWrapper").css("height","98px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "98");
    jQuery("#oneClickCallToActionHeight").val("98px");
    jQuery("p.connectorHeadline").css("font-size","23px");
    jQuery("#headlineFontSizeSlider").slider("value", "23");
    jQuery("#headlineFontSize").val("23px");
    jQuery("div.connectorDescriptionText").css("font-size","17px");
    jQuery("div.connectorDescriptionText p").css("font-size","17px");
    jQuery("div.connectorDescriptionText li").css("font-size","17px");
    jQuery("#mainFontSizeSlider").slider("value", "17");
    jQuery("#mainFontSize").val("17px");
    jQuery("p.connectorCallToAction").css("font-size","18px");
    jQuery("#callToActionFontSizeSlider").slider("value", "18");
    jQuery("#callToActionFontSize").val("18px");
    jQuery(".connectorWrapper").css("background-color","#0051BB");
    jQuery("input#connectorBGColor").miniColors('value', ["#0051BB"]);
    jQuery(".optinWrapper").css("background-color","#564DBA");
    jQuery("input#OptinBGColor").miniColors('value', ["#564DBA"]);
    jQuery("p.connecterHeadline").css("color","#ffffff");
    jQuery("input#headlineTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("border-color","#1F0101");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#1F0101"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#ffffff");
    jQuery("input#callToActionTextColor").miniColors('value', ["#ffffff"]);
    jQuery("a#emailSignUpButton").css("color","#FFFFFF");
    jQuery("a#oneClickSignupButton").css("color","#FFFFFF");
    jQuery("input#buttonFontColor").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #fffffc");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #fffffc");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #fffffc");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#fffffc"]);
    jQuery("a.navButton").css("border-color","#000000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#000000"]);
    jQuery("div.connectorDescriptionText").css("color","#ffffff");
    jQuery("div.connectorDescriptionText p").css("color","#ffffff");
    jQuery("div.connectorDescriptionText li").css("color","#ffffff");
    jQuery("input#bodyTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#000000");
    jQuery("input#borderColor").miniColors('value', ["#000000"]);
    jQuery(".optinGraphic").css("margin-top","-33px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-33");
    jQuery("#imageVerticalPosition").val("-33px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","Droid Sans");
    jQuery("select#headlineFont").val("Droid Sans");
    jQuery("input.connectorInputFields").css("font-family","berlin Sans FB");
    jQuery("select#inputTextFont").val("berlin Sans FB");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Droid Sans");
    jQuery("select#callToActionFont").val("Droid Sans");
    jQuery("div.connectorDescriptionText").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText p").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText li").css("font-family","berlin Sans FB");
    jQuery("select#bodyFont").val("berlin Sans FB");
    jQuery(".navButton").css("background","#FFB30F");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#FFB30F), to(#cd8f0c))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #cd8f0c 5%, #FFB30F 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#FFB30F', endColorstr='#cd8f0c'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#FFB30F"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("Enter your Name and Email Address Below");
    jQuery("#emailCallToActionText").val("Enter your Name and Email Address Below");
    jQuery("p.facebookCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#facebookCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.oneClickCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#oneClickCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("div.connectorDescriptionText").text("Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.");
    tinyMCE.activeEditor.setContent('Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.');
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("#sidePictureShow").attr("checked", true);
}
function defaultStyle4() {
    jQuery("#hc_default_template").val(4);
    resetUnusedClasses();
    jQuery(".connectorWrapper").css("height","107px");
    jQuery("#connectorHeightSlider").slider("value", "107");
    jQuery("#connectorHeight").val("107px");
    jQuery(".connectorWrapper").css("width","647px");
    jQuery("#connectorWidthSlider").slider("value", "647");
    jQuery("#connectorWidth").val("647px");
    jQuery(".optinWrapper").css("height","107px");
    jQuery("#callToActionHeightSlider").slider("value", "107");
    jQuery("#callToActionHeight").val("107px");
    jQuery(".emailConnectorWrapper").css("height","107px");
    jQuery("#emailBoxHeightSlider").slider("value", "107");
    jQuery("#emailBoxHeight").val("107px");
    jQuery(".facebookConnectorWrapper").css("height","107px");
    jQuery("#facebookBoxHeightSlider").slider("value", "107");
    jQuery("#facebookBoxHeight").val("107px");
    jQuery(".oneClickConnectorWrapper").css("height","107px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "107");
    jQuery("#oneClickBoxHeight").val("107px");
    jQuery(".emailOptinWrapper").css("height","107px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "107");
    jQuery("#emailCallToActionHeight").val("107px");
    jQuery(".facebookOptinWrapper").css("height","107px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "107");
    jQuery("#facebookCallToActionHeight").val("107px");
    jQuery(".oneClickOptinWrapper").css("height","107px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "107");
    jQuery("#oneClickCallToActionHeight").val("107px");
    jQuery("p.connectorHeadline").css("font-size","25px");
    jQuery("#headlineFontSizeSlider").slider("value", "25");
    jQuery("#headlineFontSize").val("25px");
    jQuery("div.connectorDescriptionText").css("font-size","18px");
    jQuery("div.connectorDescriptionText p").css("font-size","18px");
    jQuery("div.connectorDescriptionText li").css("font-size","18px");
    jQuery("#mainFontSizeSlider").slider("value", "18");
    jQuery("#mainFontSize").val("18px");
    jQuery("p.connectorCallToAction").css("font-size","20px");
    jQuery("#callToActionFontSizeSlider").slider("value", "20");
    jQuery("#callToActionFontSize").val("20px");
    jQuery(".connectorWrapper").css("background-color","#FFFFFF");
    jQuery("input#connectorBGColor").miniColors('value', ["#FFFFFF"]);
    jQuery(".optinWrapper").css("background-color","#DBD4D4");
    jQuery("input#OptinBGColor").miniColors('value', ["#DBD4D4"]);
    jQuery("p.connecterHeadline").css("color","#ffffff");
    jQuery("input#headlineTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("border-color","#920000");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#920000"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#000000");
    jQuery("input#callToActionTextColor").miniColors('value', ["#000000"]);
    jQuery("a#emailSignUpButton").css("color","#ffffff");
    jQuery("a#oneClickSignupButton").css("color","#ffffff");
    jQuery("input#buttonFontColor").miniColors('value', ["#ffffff"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("border-color","#000000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#000000"]);
    jQuery("div.connectorDescriptionText").css("color","#ffffff");
    jQuery("div.connectorDescriptionText p").css("color","#ffffff");
    jQuery("div.connectorDescriptionText li").css("color","#ffffff");
    jQuery("input#bodyTextColor").miniColors('value', ["#ffffff"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#000000");
    jQuery("input#borderColor").miniColors('value', ["#000000"]);
    jQuery(".optinGraphic").css("margin-top","-30px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-30");
    jQuery("#imageVerticalPosition").val("-30px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","Verdana");
    jQuery("select#headlineFont").val("Verdana");
    jQuery("input.connectorInputFields").css("font-family","Droid Sans");
    jQuery("select#inputTextFont").val("Droid Sans");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Droid Serif");
    jQuery("select#callToActionFont").val("Droid Serif");
    jQuery("div.connectorDescriptionText").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText p").css("font-family","berlin Sans FB");
    jQuery("div.connectorDescriptionText li").css("font-family","berlin Sans FB");
    jQuery("select#bodyFont").val("berlin Sans FB");
    jQuery(".navButton").css("background","#299100");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#299100), to(#207400))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #207400 5%, #299100 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#299100', endColorstr='#207400'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#299100"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").hide();
    jQuery("img.optinGraphic").css("display","none");
    jQuery("#sidePictureShow").attr("checked", false);
    jQuery("tr#arrowGraphicsShowRow").show();
    jQuery("#arrowGraphicsShow").attr("checked", true);
    jQuery("img.leftArrow").css("display","block");
    jQuery("img.rightArrow").css("display","block");
    jQuery("img.leftArrow").attr("src", "<?php echo HYBRIDCONNECT_IAMGES_PATH ?>/arrow-1-red-l.png");
    jQuery("img.rightArrow").attr("src","<?php echo HYBRIDCONNECT_IAMGES_PATH ?>/arrow-1-red-r.png");
    jQuery("p.emailCallToAction").text("Enter your Name and Email Address Below");
    jQuery("#emailCallToActionText").val("Enter your Name and Email Address Below");
    jQuery("p.facebookCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#facebookCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.oneClickCallToAction").text("Click the Button Below to Sign Up");
    jQuery("#oneClickCallToActionText").val("Click the Button Below to Sign Up");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("div.connectorDescriptionText").text("");
    tinyMCE.activeEditor.setContent('');
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
    hc_selected_arrow_src = "<?php echo HYBRIDCONNECT_IAMGES_PATH?>/arrow-1-red-";
}
function defaultStyle5() {
    jQuery("#hc_default_template").val(5);
    resetUnusedClasses();
    jQuery(".connectorWrapper").css("height","213px");
    jQuery("#connectorHeightSlider").slider("value", "213");
    jQuery("#connectorHeight").val("213px");
    jQuery(".connectorWrapper").css("width","647px");
    jQuery("#connectorWidthSlider").slider("value", "647");
    jQuery("#connectorWidth").val("647px");
    jQuery(".optinWrapper").css("height","102px");
    jQuery("#callToActionHeightSlider").slider("value", "102");
    jQuery("#callToActionHeight").val("102px");
    jQuery(".emailConnectorWrapper").css("height","213px");
    jQuery("#emailBoxHeightSlider").slider("value", "213");
    jQuery("#emailBoxHeight").val("213px");
    jQuery(".facebookConnectorWrapper").css("height","213px");
    jQuery("#facebookBoxHeightSlider").slider("value", "213");
    jQuery("#facebookBoxHeight").val("213px");
    jQuery(".oneClickConnectorWrapper").css("height","213px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "213");
    jQuery("#oneClickBoxHeight").val("213px");
    jQuery(".emailOptinWrapper").css("height","102px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "102");
    jQuery("#emailCallToActionHeight").val("102px");
    jQuery(".facebookOptinWrapper").css("height","102px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "102");
    jQuery("#facebookCallToActionHeight").val("102px");
    jQuery(".oneClickOptinWrapper").css("height","102px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "102");
    jQuery("#oneClickCallToActionHeight").val("102px");
    jQuery("p.connectorHeadline").css("font-size","25px");
    jQuery("#headlineFontSizeSlider").slider("value", "25");
    jQuery("#headlineFontSize").val("25px");
    jQuery("div.connectorDescriptionText").css("font-size","18px");
    jQuery("div.connectorDescriptionText p").css("font-size","18px");
    jQuery("div.connectorDescriptionText li").css("font-size","18px");
    jQuery("#mainFontSizeSlider").slider("value", "18");
    jQuery("#mainFontSize").val("18px");
    jQuery("p.connectorCallToAction").css("font-size","22px");
    jQuery("#callToActionFontSizeSlider").slider("value", "22");
    jQuery("#callToActionFontSize").val("22px");
    jQuery(".connectorWrapper").css("background-color","#F7F7F7");
    jQuery("input#connectorBGColor").miniColors('value', ["#F7F7F7"]);
    jQuery(".optinWrapper").css("background-color","#F0F0F0");
    jQuery("input#OptinBGColor").miniColors('value', ["#F0F0F0"]);
    jQuery("p.connecterHeadline").css("color","#9E0000");
    jQuery("input#headlineTextColor").miniColors('value', ["#9E0000"]);
    jQuery("input.connectorInputFields").css("border-color","#920000");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#920000"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#9E0000");
    jQuery("input#callToActionTextColor").miniColors('value', ["#9E0000"]);
    jQuery("a#emailSignUpButton").css("color","#FFFFFF");
    jQuery("a#oneClickSignupButton").css("color","#FFFFFF");
    jQuery("input#buttonFontColor").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#F06C6C"]);
    jQuery("a.navButton").css("border-color","#940000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#940000"]);
    jQuery("div.connectorDescriptionText").css("color","#000000");
    jQuery("div.connectorDescriptionText p").css("color","#000000");
    jQuery("div.connectorDescriptionText li").css("color","#000000");
    jQuery("input#bodyTextColor").miniColors('value', ["#000000"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#AD9393");
    jQuery("input#borderColor").miniColors('value', ["#AD9393"]);
    jQuery(".optinGraphic").css("margin-top","-30px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-30");
    jQuery("#imageVerticalPosition").val("-30px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","PT Sans Narrow");
    jQuery("select#headlineFont").val("PT Sans Narrow");
    jQuery("input.connectorInputFields").css("font-family","Droid Sans");
    jQuery("select#inputTextFont").val("Droid Sans");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","PT Sans Narrow");
    jQuery("select#callToActionFont").val("PT Sans Narrow");
    jQuery("div.connectorDescriptionText").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText p").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText li").css("font-family","PT Sans Narrow");
    jQuery("select#bodyFont").val("PT Sans Narrow");
    jQuery(".navButton").css("background","#DE0000");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#DE0000), to(#b20000))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #b20000 5%, #DE0000 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#DE0000', endColorstr='#b20000'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#DE0000"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").hide();
    jQuery("img.optinGraphic").css("display","none");
    jQuery("#sidePictureShow").attr("checked", false);
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("Enter your Name and Email Address Below");
    jQuery("#emailCallToActionText").val("Enter your Name and Email Address Below");
    jQuery("p.facebookCallToAction").text("Connect With Facebook");
    jQuery("#facebookCallToActionText").val("Connect With Facebook");
    jQuery("p.oneClickCallToAction").text("Sign Up by Clicking the Button");
    jQuery("#oneClickCallToActionText").val("Sign Up by Clicking the Button");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("div.connectorDescriptionText").text("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!  Try and keep your description text as short as possible.");
    tinyMCE.activeEditor.setContent("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!  Try and keep your description text as short as possible.");
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
}
function defaultStyle6() {
    jQuery("#hc_default_template").val(6);
    resetUnusedClasses();
    jQuery(".connectorWrapper").css("height","164px");
    jQuery("#connectorHeightSlider").slider("value", "164");
    jQuery("#connectorHeight").val("164px");
    jQuery(".connectorWrapper").css("width","698px");
    jQuery("#connectorWidthSlider").slider("value", "698");
    jQuery("#connectorWidth").val("698px");
    jQuery(".optinWrapper").css("height","65px");
    jQuery("#callToActionHeightSlider").slider("value", "65");
    jQuery("#callToActionHeight").val("65px");
    jQuery(".emailConnectorWrapper").css("height","164px");
    jQuery("#emailBoxHeightSlider").slider("value", "164");
    jQuery("#emailBoxHeight").val("164px");
    jQuery(".facebookConnectorWrapper").css("height","164px");
    jQuery("#facebookBoxHeightSlider").slider("value", "164");
    jQuery("#facebookBoxHeight").val("164px");
    jQuery(".oneClickConnectorWrapper").css("height","164px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "164");
    jQuery("#oneClickBoxHeight").val("164px");
    jQuery(".emailOptinWrapper").css("height","65px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "65");
    jQuery("#emailCallToActionHeight").val("65px");
    jQuery(".facebookOptinWrapper").css("height","65px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "65");
    jQuery("#facebookCallToActionHeight").val("65px");
    jQuery(".oneClickOptinWrapper").css("height","65px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "65");
    jQuery("#oneClickCallToActionHeight").val("65px");
    jQuery("p.connectorHeadline").css("font-size","27px");
    jQuery("#headlineFontSizeSlider").slider("value", "27");
    jQuery("#headlineFontSize").val("27px");
    jQuery("div.connectorDescriptionText").css("font-size","16px");
    jQuery("div.connectorDescriptionText p").css("font-size","16px");
    jQuery("div.connectorDescriptionText li").css("font-size","16px");
    jQuery("#mainFontSizeSlider").slider("value", "16");
    jQuery("#mainFontSize").val("16px");
    jQuery("p.connectorCallToAction").css("font-size","22px");
    jQuery("#callToActionFontSizeSlider").slider("value", "22");
    jQuery("#callToActionFontSize").val("22px");
    jQuery(".connectorWrapper").css("background-color","#F7F7F7");
    jQuery("input#connectorBGColor").miniColors('value', ["#F7F7F7"]);
    jQuery(".optinWrapper").css("background-color","#F0F0F0");
    jQuery("input#OptinBGColor").miniColors('value', ["#F0F0F0"]);
    jQuery("p.connecterHeadline").css("color","#00942A");
    jQuery("input#headlineTextColor").miniColors('value', ["#00942A"]);
    jQuery("input.connectorInputFields").css("border-color","#BFB0B0");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#BFB0B0"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#9E0000");
    jQuery("input#callToActionTextColor").miniColors('value', ["#9E0000"]);
    jQuery("a#emailSignUpButton").css("color","#ffffff");
    jQuery("a#oneClickSignupButton").css("color","#ffffff");
    jQuery("input#buttonFontColor").miniColors('value', ["#ffffff"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("border-color","#000000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#000000"]);
    jQuery("div.connectorDescriptionText").css("color","#000000");
    jQuery("div.connectorDescriptionText p").css("color","#000000");
    jQuery("div.connectorDescriptionText li").css("color","#000000");
    jQuery("input#bodyTextColor").miniColors('value', ["#000000"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#D4D4D4");
    jQuery("input#borderColor").miniColors('value', ["#D4D4D4"]);
    jQuery(".optinGraphic").css("margin-top","-85px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-85");
    jQuery("#imageVerticalPosition").val("-85px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","169px");
    jQuery("#nameFieldLengthSlider").slider("value", "169");
    jQuery("#nameFieldLength").val("169px");
    jQuery(".emailConnectorInputField").css("width","173px");
    jQuery("#emailFieldLengthSlider").slider("value", "173");
    jQuery("#emailFieldLength").val("173px");
    jQuery("p.connectorHeadline").css("font-family","Lora");
    jQuery("select#headlineFont").val("Lora");
    jQuery("input.connectorInputFields").css("font-family","Droid Sans");
    jQuery("select#inputTextFont").val("Droid Sans");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Lora");
    jQuery("select#callToActionFont").val("Lora");
    jQuery("div.connectorDescriptionText").css("font-family","Lora");
    jQuery("div.connectorDescriptionText p").css("font-family","Lora");
    jQuery("div.connectorDescriptionText li").css("font-family","Lora");
    jQuery("select#bodyFont").val("Lora");
    jQuery(".navButton").css("background","#299100");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#299100), to(#207400))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #207400 5%, #299100 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#299100', endColorstr='#207400'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#299100"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").hide();
    jQuery("img.optinGraphic").css("display","none");
    jQuery("#sidePictureShow").attr("checked", false);
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("");
    jQuery("#emailCallToActionText").val("");
    jQuery("p.facebookCallToAction").text("");
    jQuery("#facebookCallToActionText").val("");
    jQuery("p.oneClickCallToAction").text("");
    jQuery("#oneClickCallToActionText").val("");
    jQuery("p.connectorHeadline").text("Join Over 9,000+ Readers");
    jQuery("#optinBoxHeadline").val("Join Over 9,000+ Readers");
    jQuery("div.connectorDescriptionText").text("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!");
    jQuery("textarea#optinBoxDescription").val("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!");
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
}
function defaultStyle7() {
    resetUnusedClasses();
    jQuery("#hc_default_template").val(7);
    jQuery(".connectorWrapper").css("height","189px");
    jQuery("#connectorHeightSlider").slider("value", "189");
    jQuery("#connectorHeight").val("189px");
    jQuery(".connectorWrapper").css("width","188px");
    jQuery("#connectorWidthSlider").slider("value", "188");
    jQuery("#connectorWidth").val("188px");
    jQuery(".optinWrapper").css("height","146px");
    jQuery("#callToActionHeightSlider").slider("value", "146");
    jQuery("#callToActionHeight").val("146px");
    jQuery(".emailConnectorWrapper").css("height","189px");
    jQuery("#emailBoxHeightSlider").slider("value", "189");
    jQuery("#emailBoxHeight").val("189px");
    jQuery(".facebookConnectorWrapper").css("height","112px");
    jQuery("#facebookBoxHeightSlider").slider("value", "112");
    jQuery("#facebookBoxHeight").val("112px");
    jQuery(".oneClickConnectorWrapper").css("height","128px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "128");
    jQuery("#oneClickBoxHeight").val("128px");
    jQuery(".emailOptinWrapper").css("height","146px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "146");
    jQuery("#emailCallToActionHeight").val("146px");
    jQuery(".facebookOptinWrapper").css("height","71px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "71");
    jQuery("#facebookCallToActionHeight").val("71px");
    jQuery(".oneClickOptinWrapper").css("height","87px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "87");
    jQuery("#oneClickCallToActionHeight").val("87px");
    jQuery("p.connectorHeadline").css("font-size","27px");
    jQuery("#headlineFontSizeSlider").slider("value", "27");
    jQuery("#headlineFontSize").val("27px");
    jQuery("div.connectorDescriptionText").css("font-size","16px");
    jQuery("div.connectorDescriptionText p").css("font-size","16px");
    jQuery("div.connectorDescriptionText li").css("font-size","16px");
    jQuery("#mainFontSizeSlider").slider("value", "16");
    jQuery("#mainFontSize").val("16px");
    jQuery("p.connectorCallToAction").css("font-size","22px");
    jQuery("#callToActionFontSizeSlider").slider("value", "22");
    jQuery("#callToActionFontSize").val("22px");
    jQuery(".connectorWrapper").css("background-color","#F7F7F7");
    jQuery("input#connectorBGColor").miniColors('value', ["#F7F7F7"]);
    jQuery(".optinWrapper").css("background-color","#F0F0F0");
    jQuery("input#OptinBGColor").miniColors('value', ["#F0F0F0"]);
    jQuery("p.connecterHeadline").css("color","#D60000");
    jQuery("input#headlineTextColor").miniColors('value', ["#D60000"]);
    jQuery("input.connectorInputFields").css("border-color","#BFB0B0");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#BFB0B0"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#9E0000");
    jQuery("input#callToActionTextColor").miniColors('value', ["#9E0000"]);
    jQuery("a#emailSignUpButton").css("color","#FFFFFF");
    jQuery("a#oneClickSignupButton").css("color","#FFFFFF");
    jQuery("input#buttonFontColor").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#F06C6C"]);
    jQuery("a.navButton").css("border-color","#940000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#940000"]);
    jQuery("div.connectorDescriptionText").css("color","#000000");
    jQuery("div.connectorDescriptionText p").css("color","#000000");
    jQuery("div.connectorDescriptionText li").css("color","#000000");
    jQuery("input#bodyTextColor").miniColors('value', ["#000000"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#D4D4D4");
    jQuery("input#borderColor").miniColors('value', ["#D4D4D4"]);
    jQuery(".optinGraphic").css("margin-top","-85px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-85");
    jQuery("#imageVerticalPosition").val("-85px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","169px");
    jQuery("#nameFieldLengthSlider").slider("value", "169");
    jQuery("#nameFieldLength").val("169px");
    jQuery(".emailConnectorInputField").css("width","167px");
    jQuery("#emailFieldLengthSlider").slider("value", "167");
    jQuery("#emailFieldLength").val("167px");
    jQuery("p.connectorHeadline").css("font-family","Lora");
    jQuery("select#headlineFont").val("Lora");
    jQuery("input.connectorInputFields").css("font-family","Droid Sans");
    jQuery("select#inputTextFont").val("Droid Sans");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Lora");
    jQuery("select#callToActionFont").val("Lora");
    jQuery("div.connectorDescriptionText").css("font-family","Lora");
    jQuery("div.connectorDescriptionText p").css("font-family","Lora");
    jQuery("div.connectorDescriptionText li").css("font-family","Lora");
    jQuery("select#bodyFont").val("Lora");
    jQuery(".navButton").css("background","#DE0000");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#DE0000), to(#b20000))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #b20000 5%, #DE0000 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#DE0000', endColorstr='#b20000'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#DE0000"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").hide();
    jQuery("img.optinGraphic").css("display","none");
    jQuery("#sidePictureShow").attr("checked", false);
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("");
    jQuery("#emailCallToActionText").val("");
    jQuery("p.facebookCallToAction").text("");
    jQuery("#facebookCallToActionText").val("");
    jQuery("p.oneClickCallToAction").text("");
    jQuery("#oneClickCallToActionText").val("");
    jQuery("p.connectorHeadline").text("Subscribe!");
    jQuery("#optinBoxHeadline").val("Subscribe!");
    jQuery("div.connectorDescriptionText").text("");
    tinyMCE.activeEditor.setContent('');
    jQuery("#emailSignUpButton").text("Get Updates!");
    jQuery("input#emailButtonText").val("Get Updates!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
}
function defaultStyle8() {
    resetUnusedClasses();
    jQuery("#hc_default_template").val(8);
    jQuery(".connectorWrapper").css("height","241px");
    jQuery("#connectorHeightSlider").slider("value", "241");
    jQuery("#connectorHeight").val("241px");
    jQuery(".connectorWrapper").css("width","465px");
    jQuery("#connectorWidthSlider").slider("value", "465");
    jQuery("#connectorWidth").val("465px");
    jQuery(".optinWrapper").css("height","106px");
    jQuery("#callToActionHeightSlider").slider("value", "106");
    jQuery("#callToActionHeight").val("106px");
    jQuery(".emailConnectorWrapper").css("height","241px");
    jQuery("#emailBoxHeightSlider").slider("value", "241");
    jQuery("#emailBoxHeight").val("241px");
    jQuery(".facebookConnectorWrapper").css("height","241px");
    jQuery("#facebookBoxHeightSlider").slider("value", "241");
    jQuery("#facebookBoxHeight").val("241px");
    jQuery(".oneClickConnectorWrapper").css("height","241px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "241");
    jQuery("#oneClickBoxHeight").val("241px");
    jQuery(".emailOptinWrapper").css("height","106px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "106");
    jQuery("#emailCallToActionHeight").val("106px");
    jQuery(".facebookOptinWrapper").css("height","106px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "106");
    jQuery("#facebookCallToActionHeight").val("106px");
    jQuery(".oneClickOptinWrapper").css("height","106px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "106");
    jQuery("#oneClickCallToActionHeight").val("106px");
    jQuery("p.connectorHeadline").css("font-size","29px");
    jQuery("#headlineFontSizeSlider").slider("value", "29");
    jQuery("#headlineFontSize").val("29px");
    jQuery("div.connectorDescriptionText").css("font-size","18px");
    jQuery("div.connectorDescriptionText p").css("font-size","18px");
    jQuery("div.connectorDescriptionText li").css("font-size","18px");
    jQuery("#mainFontSizeSlider").slider("value", "18");
    jQuery("#mainFontSize").val("18px");
    jQuery("p.connectorCallToAction").css("font-size","22px");
    jQuery("#callToActionFontSizeSlider").slider("value", "22");
    jQuery("#callToActionFontSize").val("22px");
    jQuery(".connectorWrapper").css("background-color","#FFFFFF");
    jQuery("input#connectorBGColor").miniColors('value', ["#FFFFFF"]);
    jQuery(".optinWrapper").css("background-color","#FFEDBF");
    jQuery("input#OptinBGColor").miniColors('value', ["#FFEDBF"]);
    jQuery("p.connecterHeadline").css("color","#9E0000");
    jQuery("input#headlineTextColor").miniColors('value', ["#9E0000"]);
    jQuery("input.connectorInputFields").css("border-color","#920000");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#920000"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#9E0000");
    jQuery("input#callToActionTextColor").miniColors('value', ["#9E0000"]);
    jQuery("a#emailSignUpButton").css("color","#ffffff");
    jQuery("a#oneClickSignupButton").css("color","#ffffff");
    jQuery("input#buttonFontColor").miniColors('value', ["#ffffff"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("border-color","#000000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#000000"]);
    jQuery("div.connectorDescriptionText").css("color","#000000");
    jQuery("div.connectorDescriptionText p").css("color","#000000");
    jQuery("div.connectorDescriptionText li").css("color","#000000");
    jQuery("input#bodyTextColor").miniColors('value', ["#000000"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#AD9393");
    jQuery("input#borderColor").miniColors('value', ["#AD9393"]);
    jQuery(".optinGraphic").css("margin-top","-30px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-30");
    jQuery("#imageVerticalPosition").val("-30px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","Anton");
    jQuery("select#headlineFont").val("Anton");
    jQuery("input.connectorInputFields").css("font-family","Droid Sans");
    jQuery("select#inputTextFont").val("Droid Sans");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Anton");
    jQuery("select#callToActionFont").val("Anton");
    jQuery("div.connectorDescriptionText").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText p").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText li").css("font-family","PT Sans Narrow");
    jQuery("select#bodyFont").val("PT Sans Narrow");
    jQuery(".navButton").css("background","#595959");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#595959), to(#474747))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #474747 5%, #595959 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#595959', endColorstr='#474747'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#595959"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").hide();
    jQuery("img.optinGraphic").css("display","none");
    jQuery("#sidePictureShow").attr("checked", false);
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("Enter Your Name and Email Address Below");
    jQuery("#emailCallToActionText").val("Enter Your Name and Email Address Below");
    jQuery("p.facebookCallToAction").text("Click to Connect with Facebook");
    jQuery("#facebookCallToActionText").val("Click to Connect with Facebook");
    jQuery("p.oneClickCallToAction").text("Click the Button Below to Start Now!");
    jQuery("#oneClickCallToActionText").val("Click the Button Below to Start Now!");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("div.connectorDescriptionText").text("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!  Try and keep your description text as short as possible.");
    tinyMCE.activeEditor.setContent("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!  Try and keep your description text as short as possible.");
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "2px");
    jQuery("#borderWidthSlider").slider("value", "2");
    jQuery("#borderWidth").val("2px");
}
function defaultStyle9() {
    resetUnusedClasses();
    jQuery("#hc_default_template").val(9);
    // additional functions specific to this style DO NOT DELETE.
    /* add background image */
    jQuery(".connectorWrapper").css("background-image","url('<?php echo HYBRIDCONNECT_IAMGES_PATH?>/semiTransparentDownArrowWhite.png')");
    jQuery(".connectorWrapper").css("background-repeat","no-repeat");
    jQuery(".connectorWrapper").css("background-position","right top");
    jQuery(".connectorDescriptionText").css("padding-right","180px");
    // end of additional functions
    jQuery(".connectorWrapper").css("height","189px");
    jQuery("#connectorHeightSlider").slider("value", "189");
    jQuery("#connectorHeight").val("189px");
    jQuery(".connectorWrapper").css("width","553px");
    jQuery("#connectorWidthSlider").slider("value", "553");
    jQuery("#connectorWidth").val("553px");
    jQuery(".optinWrapper").css("height","61px");
    jQuery("#callToActionHeightSlider").slider("value", "61");
    jQuery("#callToActionHeight").val("61px");
    jQuery(".emailConnectorWrapper").css("height","189px");
    jQuery("#emailBoxHeightSlider").slider("value", "189");
    jQuery("#emailBoxHeight").val("189px");
    jQuery(".facebookConnectorWrapper").css("height","189px");
    jQuery("#facebookBoxHeightSlider").slider("value", "189");
    jQuery("#facebookBoxHeight").val("189px");
    jQuery(".oneClickConnectorWrapper").css("height","189px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "189");
    jQuery("#oneClickBoxHeight").val("189px");
    jQuery(".emailOptinWrapper").css("height","61px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "61");
    jQuery("#emailCallToActionHeight").val("61px");
    jQuery(".facebookOptinWrapper").css("height","61px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "61");
    jQuery("#facebookCallToActionHeight").val("61px");
    jQuery(".oneClickOptinWrapper").css("height","61px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "61");
    jQuery("#oneClickCallToActionHeight").val("61px");
    jQuery("p.connectorHeadline").css("font-size","23px");
    jQuery("#headlineFontSizeSlider").slider("value", "23");
    jQuery("#headlineFontSize").val("23px");
    jQuery("div.connectorDescriptionText").css("font-size","18px");
    jQuery("div.connectorDescriptionText p").css("font-size","18px");
    jQuery("div.connectorDescriptionText li").css("font-size","18px");
    jQuery("#mainFontSizeSlider").slider("value", "18");
    jQuery("#mainFontSize").val("18px");
    jQuery("p.connectorCallToAction").css("font-size","22px");
    jQuery("#callToActionFontSizeSlider").slider("value", "22");
    jQuery("#callToActionFontSize").val("22px");
    jQuery(".connectorWrapper").css("background-color","#C90404");
    jQuery("input#connectorBGColor").miniColors('value', ["#C90404"]);
    jQuery(".optinWrapper").css("background-color","#C90202");
    jQuery("input#OptinBGColor").miniColors('value', ["#C90202"]);
    jQuery("p.connecterHeadline").css("color","#FFFFFF");
    jQuery("input#headlineTextColor").miniColors('value', ["#FFFFFF"]);
    jQuery("input.connectorInputFields").css("border-color","#920000");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#920000"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#9E0000");
    jQuery("input#callToActionTextColor").miniColors('value', ["#9E0000"]);
    jQuery("a#emailSignUpButton").css("color","#ffffff");
    jQuery("a#oneClickSignupButton").css("color","#ffffff");
    jQuery("input#buttonFontColor").miniColors('value', ["#ffffff"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #FFFFFF");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("border-color","#000000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#000000"]);
    jQuery("div.connectorDescriptionText").css("color","#FFFFFF");
    jQuery("div.connectorDescriptionText p").css("color","#FFFFFF");
    jQuery("div.connectorDescriptionText li").css("color","#FFFFFF");
    jQuery("input#bodyTextColor").miniColors('value', ["#FFFFFF"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#9E0606");
    jQuery("input#borderColor").miniColors('value', ["#9E0606"]);
    jQuery(".optinGraphic").css("margin-top","-30px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-30");
    jQuery("#imageVerticalPosition").val("-30px");
    jQuery(".optinGraphic").css("margin-left","0px");
    jQuery("#imageLeftMarginSlider").slider("value", "0");
    jQuery("#imageLeftMargin").val("0px");
    jQuery(".optinGraphic").css("margin-right","0px");
    jQuery("#imageRightMarginSlider").slider("value", "0");
    jQuery("#imageRightMargin").val("0px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","Lora");
    jQuery("select#headlineFont").val("Lora");
    jQuery("input.connectorInputFields").css("font-family","Droid Sans");
    jQuery("select#inputTextFont").val("Droid Sans");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Ubuntu");
    jQuery("select#callToActionFont").val("Ubuntu");
    jQuery("div.connectorDescriptionText").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText p").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText li").css("font-family","PT Sans Narrow");
    jQuery("select#bodyFont").val("PT Sans Narrow");
    jQuery(".navButton").css("background","#299100");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#299100), to(#207400))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #207400 5%, #299100 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#299100', endColorstr='#207400'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#299100"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").hide();
    jQuery("img.optinGraphic").css("display","none");
    jQuery("#sidePictureShow").attr("checked", false);
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("");
    jQuery("#emailCallToActionText").val("");
    jQuery("p.facebookCallToAction").text("");
    jQuery("#facebookCallToActionText").val("");
    jQuery("p.oneClickCallToAction").text("");
    jQuery("#oneClickCallToActionText").val("");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("p.connectorDescriptionText").text("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!  Try and keep your description text as short as possible.");
    jQuery("textarea#optinBoxDescription").val("Enter benefits for why the user should sign up for your product/service - don't talk features, but talk benefits!  Try and keep your description text as short as possible.");
    jQuery("#emailSignUpButton").text("Send Me Updates!");
    jQuery("input#emailButtonText").val("Send Me Updates!");
    jQuery("#oneClickSignupButton").text("Send Me Updates!");
    jQuery("input#oneClickButtonText").val("Send Me Updates!");
    jQuery("div.connectorWrapper").css("border-width", "10px");
    jQuery("#borderWidthSlider").slider("value", "10");
    jQuery("#borderWidth").val("10px");
}
function defaultStyle10() {
    jQuery("#hc_default_template").val(10);
    resetUnusedClasses();
    // custom changes
    var div1Html = jQuery('.emailOptinWrapper').html();
    jQuery('.emailOptinWrapper').css("display","none");
    jQuery('#sideOptinPosition').html(div1Html);
    jQuery('#sideOptinPosition').css("display","block");
    jQuery('.optinPosition').css("text-align","center");
    jQuery('.emailCallToAction').css("text-align","center");
    var div1Html = jQuery('.facebookOptinWrapper').html();
    jQuery('.facebookOptinWrapper').css("display","none");
    jQuery('#sideFacebookPosition').html(div1Html);
    jQuery('#sideFacebookPosition').css("display", "block");
    jQuery('.facebookPosition').css("text-align","center");
    jQuery('.facebookCallToAction').css("text-align","center");
    var div1Html = jQuery('.oneClickOptinWrapper').html();
    jQuery('.oneClickOptinWrapper').css("display","none");
    jQuery('#sideOneClickPosition').html(div1Html);
    jQuery('#sideOneClickPosition').css("display","block");
    jQuery('.oneClickPosition').css("text-align","center");
    jQuery('.oneClickCallToAction').css("text-align","center");
    jQuery(".connectorWrapper").css("height","343px");
    jQuery("#connectorHeightSlider").slider("value", "343");
    jQuery("#connectorHeight").val("343px");
    jQuery(".connectorWrapper").css("width","584px");
    jQuery("#connectorWidthSlider").slider("value", "584");
    jQuery("#connectorWidth").val("584px");
    jQuery(".optinWrapper").css("height","98px");
    jQuery("#callToActionHeightSlider").slider("value", "98");
    jQuery("#callToActionHeight").val("98px");
    jQuery(".emailConnectorWrapper").css("height","343px");
    jQuery("#emailBoxHeightSlider").slider("value", "343");
    jQuery("#emailBoxHeight").val("343px");
    jQuery(".facebookConnectorWrapper").css("height","204px");
    jQuery("#facebookBoxHeightSlider").slider("value", "204");
    jQuery("#facebookBoxHeight").val("204px");
    jQuery(".oneClickConnectorWrapper").css("height","230px");
    jQuery("#oneClickBoxHeightSlider").slider("value", "230");
    jQuery("#oneClickBoxHeight").val("230px");
    jQuery(".emailOptinWrapper").css("height","98px");
    jQuery("#emailCallToActionHeightSlider").slider("value", "98");
    jQuery("#emailCallToActionHeight").val("98px");
    jQuery(".facebookOptinWrapper").css("height","98px");
    jQuery("#facebookCallToActionHeightSlider").slider("value", "98");
    jQuery("#facebookCallToActionHeight").val("98px");
    jQuery(".oneClickOptinWrapper").css("height","98px");
    jQuery("#oneClickCallToActionHeightSlider").slider("value", "98");
    jQuery("#oneClickCallToActionHeight").val("98px");
    jQuery("p.connectorHeadline").css("font-size","35px");
    jQuery("#headlineFontSizeSlider").slider("value", "35");
    jQuery("#headlineFontSize").val("35px");
    jQuery("div.connectorDescriptionText").css("font-size","19px");
    jQuery("div.connectorDescriptionText p").css("font-size","19px");
    jQuery("div.connectorDescriptionText li").css("font-size","19px");
    jQuery("#mainFontSizeSlider").slider("value", "19");
    jQuery("#mainFontSize").val("19px");
    jQuery("p.connectorCallToAction").css("font-size","20px");
    jQuery("#callToActionFontSizeSlider").slider("value", "20");
    jQuery("#callToActionFontSize").val("20px");
    jQuery(".connectorWrapper").css("background-color","#FFFFCC");
    jQuery("input#connectorBGColor").miniColors('value', ["#FFFFCC"]);
    jQuery(".optinWrapper").css("background-color","#FFFFCC");
    jQuery("input#OptinBGColor").miniColors('value', ["#FFFFCC"]);
    jQuery("p.connecterHeadline").css("color","#3B3B3B");
    jQuery("input#headlineTextColor").miniColors('value', ["#3B3B3B"]);
    jQuery("input.connectorInputFields").css("border-color","#E0D05A");
    jQuery("input#inputFieldBorderColor").miniColors('value', ["#E0D05A"]);
    jQuery("input.connectorInputFields").css("background","#ffffff");
    jQuery("input#inputFieldBackgroundColor").miniColors('value', ["#ffffff"]);
    jQuery("p.connectorCallToAction").css("color","#000000");
    jQuery("input#callToActionTextColor").miniColors('value', ["#000000"]);
    jQuery("a#emailSignUpButton").css("color","#FFFFFF");
    jQuery("a#oneClickSignupButton").css("color","#FFFFFF");
    jQuery("input#buttonFontColor").miniColors('value', ["#FFFFFF"]);
    jQuery("a.navButton").css("text-shadow","#000000");
    jQuery("input#buttonTextShadowColor").miniColors('value', ["#000000"]);
    jQuery("a.navButton").css("-moz-box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("a.navButton").css("-webkit-box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("a.navButton").css("box-shadow","inset 0px 1px 0px 0px #F06C6C");
    jQuery("input#buttonBoxShadow").miniColors('value', ["#F06C6C"]);
    jQuery("a.navButton").css("border-color","#940000");
    jQuery("input#buttonBorderColor").miniColors('value', ["#940000"]);
    jQuery("div.connectorDescriptionText").css("color","#2E2D2D");
    jQuery("div.connectorDescriptionText p").css("color","#2E2D2D");
    jQuery("div.connectorDescriptionText li").css("color","#2E2D2D");
    jQuery("input#bodyTextColor").miniColors('value', ["#2E2D2D"]);
    jQuery("input.connectorInputFields").css("color","#000000");
    jQuery("input#inputTextColor").miniColors('value', ["#000000"]);
    jQuery(".connectorWrapper").css("border-color","#F2F7B7");
    jQuery("input#borderColor").miniColors('value', ["#F2F7B7"]);
    jQuery(".optinGraphic").css("margin-top","-48px");
    jQuery("#imageVerticalPositionSlider").slider("value", "-48");
    jQuery("#imageVerticalPosition").val("-48px");
    jQuery(".optinGraphic").css("margin-left","24px");
    jQuery("#imageLeftMarginSlider").slider("value", "24");
    jQuery("#imageLeftMargin").val("24px");
    jQuery(".optinGraphic").css("margin-right","-8px");
    jQuery("#imageRightMarginSlider").slider("value", "-8");
    jQuery("#imageRightMargin").val("-8px");
    jQuery(".nameConnectorInputField").css("width","140px");
    jQuery("#nameFieldLengthSlider").slider("value", "140");
    jQuery("#nameFieldLength").val("140px");
    jQuery(".emailConnectorInputField").css("width","140px");
    jQuery("#emailFieldLengthSlider").slider("value", "140");
    jQuery("#emailFieldLength").val("140px");
    jQuery("p.connectorHeadline").css("font-family","Lobster");
    jQuery("select#headlineFont").val("Lobster");
    jQuery("input.connectorInputFields").css("font-family","berlin Sans FB");
    jQuery("select#inputTextFont").val("berlin Sans FB");
    jQuery("a.navButton").css("font-family","Arial");
    jQuery("select#buttonTextFont").val("Arial");
    jQuery("p.connectorCallToAction").css("font-family","Dosis");
    jQuery("select#callToActionFont").val("Dosis");
    jQuery("div.connectorDescriptionText").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText p").css("font-family","PT Sans Narrow");
    jQuery("div.connectorDescriptionText li").css("font-family","PT Sans Narrow");
    jQuery("select#bodyFont").val("PT Sans Narrow");
    jQuery(".navButton").css("background","#DE0000");
    jQuery(".navButton").css("background","-webkit-gradient(linear, left top, left bottom, from(#DE0000), to(#b20000))");
    jQuery(".navButton").css("background","-moz-linear-gradient( center top, #b20000 5%, #DE0000 100% ");
    jQuery(".navButton").css("filter","progid:DXImageTransform.Microsoft.gradient(startColorstr='#DE0000', endColorstr='#b20000'");
    jQuery("input#buttonBackgroundColor").miniColors('value', ["#DE0000"]);
    jQuery("div.emailOptinWrapper").css("text-align", "center");
    jQuery("#emailCentre").attr("checked", true);
    jQuery("div.facebookOptinWrapper").css("text-align", "center");
    jQuery("#facebookCentre").attr("checked", true);
    jQuery("div.oneClickOptinWrapper").css("text-align", "center");
    jQuery("#oneClickCentre").attr("checked", true);
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("#sidePictureShow").attr("checked", true);
    jQuery("tr#arrowGraphicsShowRow").hide();
    jQuery("img.leftArrow").css("display","none");
    jQuery("img.rightArrow").css("display","none");
    jQuery("#arrowGraphicsShow").attr("checked", false);
    jQuery("p.emailCallToAction").text("Sign Up Below:-");
    jQuery("#emailCallToActionText").val("Sign Up Below:-");
    jQuery("p.facebookCallToAction").text("");
    jQuery("#facebookCallToActionText").val("");
    jQuery("p.oneClickCallToAction").text("");
    jQuery("#oneClickCallToActionText").val("");
    jQuery("p.connectorHeadline").text("Want Some More Free Updates?");
    jQuery("#optinBoxHeadline").val("Want Some More Free Updates?");
    jQuery("p.connectorDescriptionText").text("Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.");
    jQuery("textarea#optinBoxDescription").val("Description of your opt in goes here. You can add multiple lines to your opt in box if you prefer. Make sure you list the benefits of why people should sign up to your list.");
    jQuery("#emailSignUpButton").text("Sign Me Up!");
    jQuery("input#emailButtonText").val("Sign Me Up!");
    jQuery("#oneClickSignupButton").text("Click Here for One Click Sign Up!");
    jQuery("input#oneClickButtonText").val("Click Here for One Click Sign Up!");
    jQuery("div.connectorWrapper").css("border-width", "8px");
    jQuery("#borderWidthSlider").slider("value", "8");
    jQuery("#borderWidth").val("8px");
    jQuery("tr.imageSettings").show();
    jQuery("img.optinGraphic").css("display","block");
    jQuery("#sidePictureShow").attr("checked", true);
}
function resetUnusedClasses() {
    jQuery('#sideOptinPosition').css("display","none");
    jQuery('.emailOptinWrapper').css("display","block");
    jQuery('.optinPosition').css("text-align","");
    jQuery('.emailCallToAction').css("text-align","");
    jQuery('#sideFacebookPosition').css("display","none");
    jQuery('.facebookOptinWrapper').css("display","block");
    jQuery('.facebookPosition').css("text-align","");
    jQuery('.facebookCallToAction').css("text-align","");
    jQuery('#sideOneClickPosition').css("display","none");
    jQuery('.oneClickOptinWrapper').css("display","block");
    jQuery('.oneClickPosition').css("text-align","");
    jQuery('.oneClickCallToAction').css("text-align","");
    jQuery(".connectorWrapper").css("background-image","none");
    jQuery(".connectorDescriptionText").css("padding-right","");
}
function hc_custom_javascript0() {
}
function hc_custom_javascript1() {
}
function hc_custom_javascript2() {
}
function hc_custom_javascript3() {
}
function hc_custom_javascript4() {
}
function hc_custom_javascript5() {
}
function hc_custom_javascript6() {
}
function hc_custom_javascript7() {
}
function hc_custom_javascript8() {
}
function hc_custom_javascript9() {
    jQuery(".connectorWrapper").css("background-image","url('<?php echo HYBRIDCONNECT_IAMGES_PATH?>/semiTransparentDownArrowWhite.png')");
    jQuery(".connectorWrapper").css("background-repeat","no-repeat");
    jQuery(".connectorWrapper").css("background-position","right top");
    jQuery(".connectorDescriptionText").css("padding-right","180px");
}
function hc_custom_javascript10() {
    var div1Html = jQuery('.emailOptinWrapper').html();
    jQuery('.emailOptinWrapper').css("display","none");
    jQuery('#sideOptinPosition').html(div1Html);
    jQuery('#sideOptinPosition').css("display","block");
    jQuery('.optinPosition').css("text-align","center");
    jQuery('.emailCallToAction').css("text-align","center");
    var div1Html = jQuery('.facebookOptinWrapper').html();
    jQuery('.facebookOptinWrapper').css("display","none");
    jQuery('#sideFacebookPosition').html(div1Html);
    jQuery('#sideFacebookPosition').css("display", "block");
    jQuery('.facebookPosition').css("text-align","center");
    jQuery('.facebookCallToAction').css("text-align","center");
    var div1Html = jQuery('.oneClickOptinWrapper').html();
    jQuery('.oneClickOptinWrapper').css("display","none");
    jQuery('#sideOneClickPosition').html(div1Html);
    jQuery('#sideOneClickPosition').css("display","block");
    jQuery('.oneClickPosition').css("text-align","center");
    jQuery('.oneClickCallToAction').css("text-align","center");
}
